/* Local, dependency-free working surface; shared data and fitted model for all screens. */
(() => {
  'use strict';
  const C=globalThis.FraudCore, $=id=>document.getElementById(id), escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const names=new Intl.DisplayNames(['ru'],{type:'region'}), country=c=>names.of(c)||c;
  const countryCodes=C.codes.slice().sort((a,b)=>country(a).localeCompare(country(b),'ru'));
  const num=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n);
  const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'KZT',maximumFractionDigits:0,notation:n>=1e6?'compact':'standard'}).format(n);
  const percent=n=>n===null||!Number.isFinite(n)?'—':(n*100).toFixed(1)+'%';
  const badge=a=>`<span class="badge ${a}">${a}</span>`;
  const options=(selected,all=false)=>(all?'<option value="">Все страны и территории</option>':'')+countryCodes.map(c=>`<option value="${c}" ${selected===c?'selected':''}>${escape(country(c))} (${c})</option>`).join('');
  const state={data:[],model:null,bins:null,curves:null,policy:{sensitivity:60,fpCost:10000,challengeCost:150,effectiveness:50},source:'Синтетический набор',page:0,query:'',filterAction:'',filterCountry:'',filterDate:'',filterDevice:'',minRisk:0,sort:'risk',selectedCountry:'KZ',mapMode:'count',zoom:1,pan:[0,0],last:null,sequence:0};
  let route='dashboard',toastTimer,streamTimer=null,interfaceLanguage='ru';
  const uiText={ru:{dashboard:'Дашборд',transactions:'Транзакции',simulator:'Live Demo',analytics:'Сети и графы',systemLive:'Система активна',upload:'Загрузить CSV'},kk:{dashboard:'Басқару тақтасы',transactions:'Транзакциялар',simulator:'Live Demo',analytics:'Желілер мен графтар',systemLive:'Жүйе белсенді',upload:'CSV жүктеу'},en:{dashboard:'Dashboard',transactions:'Transactions',simulator:'Live Demo',analytics:'Networks & Graphs',systemLive:'System Live',upload:'Upload CSV'}};
  function applyLanguage(language){interfaceLanguage=language;document.documentElement.lang=language;document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=uiText[language][el.dataset.i18n]||el.textContent;});document.querySelectorAll('[data-language]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.language===language)));}
  function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4000);}
  function download(text,filename,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
  function recompute(){state.bins=C.summarize(state.data);state.curves=C.curves(state.bins);$('dataset-status').textContent=`${state.source} · ${num(state.data.length)} операций · ML обучена отдельно на 12 000 синтетических примеров`;$('export-all').disabled=false;}
  function metricCard(label,value,detail,color=''){return `<div class="panel kpi"><span>${label}</span><strong class="${color}">${value}</strong><small>${detail}</small></div>`;}
  function svgPlot(series,{label='',xLabel='',yLabel='',maxY=1,maxX=100,marker=null}={}) {
    const W=600,H=235,L=58,R=18,T=15,B=40,pw=W-L-R,ph=H-T-B;
    let svg=`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${escape(label)}"><title>${escape(label)}</title>`;
    for(let i=0;i<=4;i++){const y=T+ph*i/4;svg+=`<line class="gridline" x1="${L}" y1="${y}" x2="${W-R}" y2="${y}"/><text class="axis" x="${L-8}" y="${y+4}" text-anchor="end">${maxY===1?Math.round((1-i/4)*100)+'%':num(maxY*(1-i/4))}</text>`;}
    for(let i=0;i<=4;i++)svg+=`<text class="axis" x="${L+pw*i/4}" y="${H-20}" text-anchor="middle">${Math.round(maxX*i/4)}</text>`;
    for(const s of series){const d=s.points.map((p,i)=>`${i?'L':'M'}${(L+p[0]/maxX*pw).toFixed(2)},${(T+ph-Math.max(0,Math.min(maxY,p[1]))/maxY*ph).toFixed(2)}`).join(' ');svg+=`<path class="chart-line" d="${d}" stroke="${s.color}"/>`;}
    if(marker!==null){const x=L+marker/maxX*pw;svg+=`<line x1="${x}" x2="${x}" y1="${T}" y2="${T+ph}" stroke="#3B82F6" stroke-width="2" stroke-dasharray="4 4"/><circle cx="${x}" cy="${T+10}" r="5" fill="#3B82F6" stroke="#F9FAFB" stroke-width="2"/>`;}
    return svg+`<text class="axis" x="${L}" y="${H-2}">${escape(xLabel)}</text><text class="axis" x="${W-R}" y="${H-2}" text-anchor="end">${escape(yLabel)}</text></svg>`;
  }
  function topRiskRows(limit=5){const top=[];for(const t of state.data){if(C.action(t.score,state.policy)!=='Block')continue;let at=top.findIndex(x=>t.score>x.score);if(at<0)at=top.length;if(at<limit){top.splice(at,0,t);if(top.length>limit)top.pop();}}return top;}
  function dashboardQuickResult(t){const result=$('quick-result');if(!result)return;const a=C.action(t.score,state.policy),color=a==='Block'?'#EF4444':a==='Challenge'?'#F59E0B':'#10B981',f=C.predict(t,state.model).factors.filter(x=>x.value!==0).sort((x,y)=>Math.abs(y.contribution)-Math.abs(x.contribution)).slice(0,3),max=Math.max(1,...f.map(x=>Math.abs(x.contribution)));result.className='quick-result';result.innerHTML=`<div class="quick-result-content"><div class="risk-gauge" style="--risk:${t.score};--gauge:${color}"><div><strong>${t.score.toFixed(0)}%</strong><small>RISK SCORE</small></div></div><div><p class="eyebrow">XAI PREVIEW</p><span class="verdict-block ${a}">${a==='Block'?'BLOCK TRANSACTION':a==='Challenge'?'CHALLENGE / 2FA':'APPROVE'}</span><p class="explanation">${escape(explanation(t))}</p><div>${f.map(x=>`<div class="factor"><span>${escape(x.name)}</span><div class="factor-track"><i style="width:${Math.abs(x.contribution)/max*100}%;background:${color}"></i></div><b>${x.contribution>=0?'+':''}${x.contribution.toFixed(2)}</b></div>`).join('')}</div></div></div>`;}
  function dashboardQuickDemo(){const form=$('dash-sim-form');if(!form)return;const setPreset=key=>{const presets={safe:{amount:12000,country:'KZ',deviceProfile:'known',frequency:1},risky:{amount:850000,country:'BR',deviceProfile:'vpn',frequency:14}};const p=presets[key];for(const [name,value]of Object.entries(p)){const input=form.elements.namedItem(name);input.value=value;}form.requestSubmit();};document.querySelectorAll('[data-quick-preset]').forEach(b=>b.onclick=()=>setPreset(b.dataset.quickPreset));form.onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form)),profile=v.deviceProfile;const tx={id:'DASH-'+(++state.sequence),user:'U-DASH',amount:+v.amount,average:15000,country:v.country,home:'KZ',timestamp:new Date().toISOString(),frequency:+v.frequency,newDevice:profile!=='known',vpn:profile==='vpn',newMerchant:profile!=='known',merchant:profile==='known'?'Market-12':'Transfer-99',device:profile==='known'?'Known mobile':profile==='vpn'?'VPN / Proxy':'New device',ip:profile==='vpn'?'198.51.100.74':'192.0.2.15',label:null};tx.score=C.predict(tx,state.model).score;state.last=tx;dashboardQuickResult(tx);};setPreset('risky');}
  function dashboardHome(){
    $('app').innerHTML=`<div id="kpis" class="kpis"></div><div class="dashboard-grid">
      <section class="panel tradeoff-panel"><div class="panel-head"><div><p class="eyebrow">BUSINESS OPTIMIZATION</p><h2>Financial Cost Function Trade-Off</h2></div><span id="total-cost" class="tag"></span></div><p class="tradeoff-intro">Настройте порог риска и сразу увидите баланс между пропущенным фродом и неудобством для честных клиентов.</p>
        <div class="threshold-row"><label class="field" for="sensitivity">Risk Threshold <strong id="sensitivity-value"></strong></label><strong id="threshold-caption">Sensitivity</strong><input type="range" id="sensitivity" min="0" max="100" step="1" value="${state.policy.sensitivity}"></div><div class="range-scale"><span>0.1 · меньше блокировок</span><span>0.9 · больше защиты</span></div><div class="policy-stats" id="thresholds"></div>
        <div class="tradeoff-controls"><label class="field">Цена ложной блокировки, ₸<input id="fp-cost" type="number" min="0" max="1000000" step="100" value="${state.policy.fpCost}"></label><label class="field">Цена проверки, ₸<input id="challenge-cost" type="number" min="0" max="100000" value="${state.policy.challengeCost}"></label></div><label class="field">Эффективность Challenge, %<input id="effectiveness" type="range" min="0" max="100" value="${state.policy.effectiveness}"><small id="effectiveness-label"></small></label><div class="btn-row"><button id="optimize" class="primary">Подобрать оптимум</button><button id="reset-policy">Сбросить</button></div>
        <div class="cost-visual"><div class="panel-head"><div><p class="eyebrow">LIVE CURVE</p><h3>Стоимость выбранной политики</h3></div><span class="tag">Golden point</span></div><div id="cost-chart"></div><div class="chart-legend"><span><i class="legend-dot" style="background:var(--red)"></i>Fraud Loss</span><span><i class="legend-dot" style="background:var(--gold)"></i>Customer Friction</span></div><div class="three" id="cost-values"></div></div>
      </section>
      <section class="panel live-risk-panel"><div class="panel-head"><div><p class="eyebrow">LIVE MONITORING</p><h2>Высокорисковые операции</h2></div><span class="tag">LIVE</span></div><div id="live-risk-list" class="live-risk-list"></div><div class="live-panel-footer"><a href="#transactions">Открыть таблицу 100 000 операций →</a></div></section>
      <section class="panel quick-demo"><div class="quick-demo-head"><div><p class="eyebrow">QUICK TRANSACTION SIMULATOR &amp; XAI PREVIEW</p><h2>Проверьте ИИ за несколько секунд</h2></div><p>Локальная модель и объяснение факторов — без отправки данных наружу.</p></div><div class="quick-demo-grid"><form id="dash-sim-form" class="quick-demo-form"><div class="preset-buttons"><button type="button" data-quick-preset="safe">🟢 Тест: обычная покупка</button><button type="button" data-quick-preset="risky">🔴 Тест: аномальный вход</button></div><div class="quick-fields"><label class="field">Сумма, ₸<input name="amount" type="number" min="1" max="1000000000" value="850000" required></label><label class="field">Страна<select name="country">${options('BR')}</select></label><label class="field">Тип устройства<select name="deviceProfile"><option value="known">Известное устройство</option><option value="new">Новое устройство</option><option value="vpn" selected>VPN / Proxy</option></select></label><label class="field">Операций за 10 минут<input name="frequency" type="number" min="0" max="10000" value="14" required></label></div><button class="primary quick-analyze" type="submit">ϟ Проверить ИИ</button></form><div id="quick-result" class="quick-result empty"><div><p class="eyebrow">XAI PREVIEW</p><p>Выберите сценарий или заполните поля, чтобы увидеть вердикт модели.</p></div></div></div></section>
      <section class="sr-only"><div id="quality"></div><div id="matrix"></div><div id="label-note"></div><span id="ap"></span><span id="auc"></span><div id="pr-chart"></div><div id="roc-chart"></div><div id="timeline"></div><button id="stream" type="button">Поток</button></section>
    </div>`;
    $('sensitivity').oninput=e=>{state.policy.sensitivity=+e.target.value;updateDashboard();};
    for(const [id,key]of [['fp-cost','fpCost'],['challenge-cost','challengeCost'],['effectiveness','effectiveness']])$(id).oninput=e=>{if(e.target.value!==''&&e.target.checkValidity()){state.policy[key]=+e.target.value;updateDashboard();}};
    $('optimize').onclick=()=>{if(!state.bins.some(b=>b.known)){toast('Для подбора нужны метки label = 0/1.');return;}let best={s:0,c:Infinity};for(let s=0;s<=100;s++){const m=C.metrics(state.bins,{...state.policy,sensitivity:s});if(m.totalCost<best.c)best={s,c:m.totalCost};}state.policy.sensitivity=best.s;$('sensitivity').value=best.s;updateDashboard();toast('Выбран минимум расчётных потерь на текущих данных.');};
    $('reset-policy').onclick=()=>{stopStream();state.policy={sensitivity:60,fpCost:10000,challengeCost:150,effectiveness:50};dashboardHome();};
    $('stream').onclick=()=>{if(streamTimer){stopStream();return;}streamTimer=setInterval(()=>{const t=C.generate(1,81000+state.sequence++,'LIVE',Date.now())[0];t.id='LIVE-'+state.sequence;t.label=null;C.scoreData([t],state.model);state.data.push(t);recompute();updateDashboard();},1000);};
    dashboardQuickDemo();updateDashboard();
  }
  function dashboard(){
    $('app').innerHTML=`<div id="kpis" class="kpis"></div><div class="section-grid">
    <section class="panel policy-hero"><div class="hero-orbit" aria-hidden="true"></div><p class="eyebrow">ПОЛИТИКА РИСКА</p><h2>Защита без лишних блокировок</h2><p class="muted">Меняйте чувствительность и наблюдайте, как меняются решения и стоимость ошибок.</p><label class="range-label" for="sensitivity">Чувствительность <strong id="sensitivity-value"></strong></label><input type="range" id="sensitivity" min="0" max="100" step="1" value="${state.policy.sensitivity}"><div class="range-scale"><span>Меньше вмешательств</span><span>Больше проверок</span></div><div class="policy-stats" id="thresholds"></div>
    <div class="policy-costs"><label class="field">Цена ложной блокировки, ₸<input id="fp-cost" type="number" min="0" max="1000000" step="100" value="${state.policy.fpCost}"></label><label class="field">Цена дополнительной проверки, ₸<input id="challenge-cost" type="number" min="0" max="100000" value="${state.policy.challengeCost}"></label></div><label class="field">Предполагаемая эффективность Challenge, %<input id="effectiveness" type="range" min="0" max="100" value="${state.policy.effectiveness}"><small id="effectiveness-label"></small></label><div class="btn-row" style="margin-top:18px"><button id="optimize" class="primary">Подобрать порог</button><button id="reset-policy">Сбросить</button></div><small>Подбор на текущем наборе — сценарный анализ, не независимая оценка качества.</small></section>
    <section class="panel"><div class="panel-head"><div><p class="eyebrow">COST FUNCTION</p><h2>Цена выбранной политики</h2></div><span id="total-cost" class="tag"></span></div><div id="cost-chart"></div><div class="chart-legend"><span><i class="legend-dot" style="background:var(--red)"></i>Остаточный фрод</span><span><i class="legend-dot" style="background:var(--gold)"></i>Неудобство и проверки</span></div><div class="three" id="cost-values" style="margin-top:25px"></div><p class="small muted" style="margin-top:18px">Стоимость — сценарная оценка по известным меткам. Успех Challenge задаётся допущением; реальные возвраты денег здесь не измеряются.</p></section>
    <section class="panel"><div class="panel-head"><div><p class="eyebrow">ACTION BREAKDOWN</p><h2>Решения по операциям</h2></div></div><div id="breakdown"></div><div id="decision-rows" class="decision-rows"></div><div id="quality" class="three" style="margin-top:26px"></div></section>
    <section class="panel"><p class="eyebrow">CONFUSION MATRIX</p><h2>Блокировки и ошибки</h2><div id="matrix" class="confusion"></div><p id="label-note" class="small muted" style="margin-top:14px"></p></section>
    <section class="panel"><div class="panel-head"><h2>Precision–Recall</h2><span id="ap" class="tag"></span></div><div id="pr-chart"></div></section><section class="panel"><div class="panel-head"><h2>ROC</h2><span id="auc" class="tag"></span></div><div id="roc-chart"></div></section>
    <section class="panel full"><div class="panel-head"><div><p class="eyebrow">ВРЕМЕННАЯ ЛЕНТА</p><h2>Активность по датам</h2></div><button id="stream">▶ Добавлять поток</button></div><div id="timeline"></div><small>Поток добавляет по одной синтетической операции в секунду; метки этих событий неизвестны.</small></section></div>`;
    $('sensitivity').oninput=e=>{state.policy.sensitivity=+e.target.value;updateDashboard();};
    for(const [id,key]of [['fp-cost','fpCost'],['challenge-cost','challengeCost'],['effectiveness','effectiveness']])$(id).oninput=e=>{if(e.target.value!==''&&e.target.checkValidity()){state.policy[key]=+e.target.value;updateDashboard();}};
    $('optimize').onclick=()=>{if(!state.bins.some(b=>b.known)){toast('Для подбора нужны метки label = 0/1.');return;}let best={s:0,c:Infinity};for(let s=0;s<=100;s++){const m=C.metrics(state.bins,{...state.policy,sensitivity:s});if(m.totalCost<best.c)best={s,c:m.totalCost};}state.policy.sensitivity=best.s;$('sensitivity').value=best.s;updateDashboard();toast('Выбран минимум расчётных потерь на текущих данных.');};
    $('reset-policy').onclick=()=>{stopStream();state.policy={sensitivity:60,fpCost:10000,challengeCost:150,effectiveness:50};dashboard();};
    $('stream').onclick=()=>{if(streamTimer){stopStream();return;}streamTimer=setInterval(()=>{const t=C.generate(1,81000+state.sequence++,'LIVE',Date.now())[0];t.id='LIVE-'+state.sequence;t.label=null;C.scoreData([t],state.model);state.data.push(t);recompute();updateDashboard();},1000);$('stream').textContent='Ⅱ Остановить поток';};
    updateDashboard();
  }
  function stopStream(){clearInterval(streamTimer);streamTimer=null;if($('stream'))$('stream').textContent='▶ Добавлять поток';}
  function updateDashboard(){
    if(route!=='dashboard')return;const p=state.policy,m=C.metrics(state.bins,p),t=C.thresholds(p.sensitivity),known=m.known>0;
    $('kpis').innerHTML=metricCard('Спасённый бюджет',known?money(m.saved):'—','Предотвращённый фрод по размеченным операциям','green')+metricCard('False Positive Rate',percent(m.fpr),'Сохранённая лояльность клиентов','amber')+metricCard('Обработано за 24ч',num(m.total)+' транзакций',escape(state.source),'blue')+`<div class="panel kpi"><span>Action Breakdown</span><div id="breakdown"></div><div id="decision-rows" class="decision-rows"></div></div>`;
    $('sensitivity-value').textContent=(p.sensitivity/100).toFixed(2);$('threshold-caption').textContent=p.sensitivity+' / 100';$('effectiveness-label').textContent=p.effectiveness+'% — сценарное допущение.';
    $('thresholds').innerHTML=`<span class="badge Approve">Approve &lt; ${t.challenge.toFixed(1)}</span><span class="badge Challenge">Challenge ${t.challenge.toFixed(1)}–${t.block.toFixed(1)}</span><span class="badge Block">Block ≥ ${t.block.toFixed(1)}</span>`;
    $('total-cost').textContent=known?money(m.totalCost):'Нет меток';
    const costs=Array.from({length:51},(_,i)=>[i*2,C.metrics(state.bins,{...p,sensitivity:i*2})]);const max=Math.max(1,...costs.map(x=>Math.max(x[1].exposure,x[1].friction+x[1].challengeCost)))/1e6;
    $('cost-chart').innerHTML=known?svgPlot([{color:'#EF4444',points:costs.map(([s,m])=>[s,m.exposure/1e6])},{color:'#F59E0B',points:costs.map(([s,m])=>[s,(m.friction+m.challengeCost)/1e6])}],{label:'Стоимость ошибок при разной чувствительности',maxY:max,xLabel:'Чувствительность →',yLabel:'млн ₸',marker:p.sensitivity}):'<div class="empty">Для расчёта потерь загрузите label: 0 или 1.</div>';
    $('cost-values').innerHTML=`<div><b class="red">${known?money(m.exposure):'—'}</b><small>Остаточный фрод</small></div><div><b class="amber">${known?money(m.friction):'—'}</b><small>Ложные блокировки</small></div><div><b class="green">${money(m.challengeCost)}</b><small>Проверки</small></div>`;
    const parts=[['Approve',m.approve,'#10B981'],['Challenge',m.challenge,'#F59E0B'],['Block',m.block,'#EF4444']];
    $('breakdown').innerHTML='<div class="breakdown">'+parts.map(([a,n,c])=>`<span title="${a}: ${num(n)}" style="width:${n/m.total*100}%;background:${c}"></span>`).join('')+'</div>';
    $('decision-rows').innerHTML=parts.map(([a,n])=>`<div class="decision-row">${badge(a)}<span>${percent(n/m.total)}</span></div>`).join('');
    const live=$('live-risk-list'),topRisk=topRiskRows();if(live){live.innerHTML=topRisk.map((tx,i)=>`<button type="button" class="live-risk-item" data-live-audit="${i}"><span class="live-risk-main"><span class="risk-dot">!</span><span><strong>${escape(tx.merchant)}</strong><small>${escape(country(tx.country))} · ${money(tx.amount)}</small></span></span><span class="live-risk-side"><b>${tx.score.toFixed(0)}%</b>${badge(C.action(tx.score,p))}</span></button>`).join('')||'<p class="empty">Нет операций, соответствующих порогу Block.</p>';document.querySelectorAll('[data-live-audit]').forEach(b=>b.onclick=()=>audit(topRisk[+b.dataset.liveAudit]));}
    $('quality').innerHTML=[['Precision',m.precision],['Recall',m.recall],['F1',m.f1]].map(([s,n])=>`<div><b>${percent(n)}</b><small>${s}</small></div>`).join('');
    $('matrix').innerHTML=[['TP · фрод заблокирован',m.tp,'',known?money(m.saved)+' под блокировкой':'—'],['FP · честная операция',m.fp,'error',known?money(m.friction)+' цена неудобства':'—'],['FN · фрод без Block',m.fn,'error',known?money(m.exposure)+' остаточный риск':'—'],['TN · честная без Block',m.tn,'','Approve + Challenge']].map(([a,b,c,d])=>`<div class="${c}"><small>${a}</small><strong>${known?num(b):'—'}</strong><small>${d}</small></div>`).join('');
    $('label-note').textContent=`Размечено ${num(m.known)} из ${num(m.total)}. Для матрицы положительное решение = Block; Challenge не считается доказанным фродом.`;
    const q=state.curves;$('ap').textContent='AP '+percent(q.ap);$('auc').textContent='AUC '+percent(q.roc);
    $('pr-chart').innerHTML=q.ap===null?'<p class="muted">Нет положительных меток.</p>':svgPlot([{color:'#10B981',points:q.points.map(p=>[p.recall*100,p.precision])}],{label:'Precision Recall по размеченным операциям',xLabel:'Recall, %',yLabel:'Precision'});
    $('roc-chart').innerHTML=q.roc===null?'<p class="muted">Нужны метки обоих классов.</p>':svgPlot([{color:'#456175',points:[[0,0],[100,1]]},{color:'#3B82F6',points:q.points.map(p=>[p.fpr*100,p.recall])}],{label:'ROC по размеченным операциям',xLabel:'False positive rate, %',yLabel:'True positive rate'});
    const dates=new Map();for(const row of state.data){const day=row.timestamp.slice(0,10);if(!dates.has(day))dates.set(day,{total:0,flagged:0});const d=dates.get(day);d.total++;if(C.action(row.score,p)!=='Approve')d.flagged++;}
    const ds=[...dates].sort((a,b)=>a[0].localeCompare(b[0]));const top=Math.max(1,...ds.map(d=>d[1].total));
    $('timeline').innerHTML=svgPlot([{color:'#10B981',points:ds.map((d,i)=>[i,d[1].total])},{color:'#F59E0B',points:ds.map((d,i)=>[i,d[1].flagged])}],{label:'Все операции и операции с проверкой по дням',maxY:top,maxX:Math.max(1,ds.length-1),xLabel:ds[0]?.[0]+' → '+ds.at(-1)?.[0],yLabel:'операций'})+'<div class="chart-legend"><span class="green">Все операции</span><span class="amber">Challenge + Block</span></div>';
  }
  function filtered(){const q=state.query.toLowerCase().trim();const match=t=>q.startsWith('device:')?t.device.toLowerCase()===q.slice(7):q.startsWith('ip:')?t.ip.toLowerCase()===q.slice(3):!q||[t.id,t.user,t.merchant,t.ip,t.device].some(v=>v.toLowerCase().includes(q));return state.data.filter(t=>match(t)&&(!state.filterAction||C.action(t.score,state.policy)===state.filterAction)&&(!state.filterCountry||t.country===state.filterCountry)&&(!state.filterDate||t.timestamp.startsWith(state.filterDate))&&(!state.filterDevice||(state.filterDevice==='new'?t.newDevice:!t.newDevice))&&t.score>=state.minRisk).sort(state.sort==='date'?(a,b)=>b.timestamp.localeCompare(a.timestamp):state.sort==='amount'?(a,b)=>b.amount-a.amount:(a,b)=>b.score-a.score);}
  function transactions(){
    $('app').innerHTML=`<section class="panel"><div class="panel-head"><div><p class="eyebrow">TRANSACTION MONITOR</p><h2>Каждое решение можно разобрать</h2></div><button id="export-filter">↓ Текущая выборка</button></div><div class="toolbar"><label class="field">Поиск<input id="search" placeholder="ID, пользователь, получатель или IP" value="${escape(state.query)}"></label><label class="field">Решение<select id="action-filter"><option value="">Все решения</option>${['Approve','Challenge','Block'].map(a=>`<option ${state.filterAction===a?'selected':''}>${a}</option>`).join('')}</select></label><label class="field">Страна<select id="country-filter">${options(state.filterCountry,true)}</select></label></div><div class="toolbar bottom"><label class="field">Дата UTC<input id="date-filter" type="date" value="${escape(state.filterDate)}"></label><label class="field">Устройство<select id="device-filter"><option value="">Все устройства</option><option value="new" ${state.filterDevice==='new'?'selected':''}>Новое</option><option value="known" ${state.filterDevice==='known'?'selected':''}>Известное</option></select></label><label class="field">Минимальный риск, 0–100<input id="risk-filter" type="number" min="0" max="100" value="${state.minRisk}"></label><label class="field">Сортировка<select id="sort"><option value="risk">По риску ↓</option><option value="date">По дате ↓</option><option value="amount">По сумме ↓</option></select></label></div><div class="btn-row"><button id="clear-filters">Сбросить фильтры</button><span class="small muted" id="found"></span></div><div class="table-wrap" style="margin-top:14px"><table><thead><tr><th>ID / пользователь</th><th>Сумма</th><th>Получатель / страна</th><th>Время UTC</th><th>Риск</th><th>Решение</th></tr></thead><tbody id="transaction-rows"></tbody></table></div><div class="pagination"><span id="page-count" class="muted"></span><div class="btn-row"><button id="prev" aria-label="Предыдущая страница">← Назад</button><button id="next" aria-label="Следующая страница">Далее →</button></div></div></section>`;
    $('sort').value=state.sort;let timer;
    for(const [id,key]of [['search','query'],['action-filter','filterAction'],['country-filter','filterCountry'],['date-filter','filterDate'],['device-filter','filterDevice'],['risk-filter','minRisk'],['sort','sort']])$(id).oninput=e=>{if(!e.target.checkValidity())return;state[key]=key==='minRisk'?+e.target.value:e.target.value;state.page=0;clearTimeout(timer);timer=setTimeout(renderRows,100);};
    $('clear-filters').onclick=()=>{Object.assign(state,{page:0,query:'',filterAction:'',filterCountry:'',filterDate:'',filterDevice:'',minRisk:0});transactions();};
    $('prev').onclick=()=>{state.page--;renderRows();};$('next').onclick=()=>{state.page++;renderRows();};$('export-filter').onclick=()=>download(C.exportCSV(filtered(),state.policy),'ichnora-filtered.csv','text/csv;charset=utf-8');renderRows();
  }
  function renderRows(){if(route!=='transactions')return;const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/25));state.page=Math.max(0,Math.min(state.page,pages-1));const slice=rows.slice(state.page*25,state.page*25+25);
    $('found').textContent='Найдено: '+num(rows.length);$('page-count').textContent=`Страница ${state.page+1} из ${num(pages)} · по 25 операций`;$('prev').disabled=state.page===0;$('next').disabled=state.page>=pages-1;
    $('transaction-rows').innerHTML=slice.length?slice.map((t,i)=>`<tr><td><button class="row-link" data-audit="${i}">${escape(t.id)}</button><small>${escape(t.user)}</small></td><td>${money(t.amount)}</td><td>${escape(t.merchant)}<small>${escape(country(t.country))} · ${t.newDevice?'Новое':'Известное'} устройство</small></td><td>${escape(t.timestamp.slice(0,16).replace('T',' '))}</td><td><span class="riskbar"><i style="width:${t.score}%"></i></span>${t.score.toFixed(1)}</td><td>${badge(C.action(t.score,state.policy))}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Ничего не найдено. Измените фильтры.</td></tr>';
    document.querySelectorAll('[data-audit]').forEach(b=>b.onclick=()=>audit(slice[+b.dataset.audit]));
  }
  function reasons(t){const r=[];if(t.amount/t.average>3)r.push(`сумма в ${(t.amount/t.average).toFixed(1)} раза выше обычной`);if(t.frequency>=5)r.push(`${t.frequency} операций за 10 минут`);if(t.newDevice)r.push('устройство отсутствует в известной истории');if(t.country!==t.home)r.push(`страна отличается от обычной: ${country(t.home)} → ${country(t.country)}`);if(t.vpn)r.push('отмечен VPN / Proxy');if(t.newMerchant)r.push('новый для клиента получатель');return r;}
  function explanation(t){const a=C.action(t.score,state.policy),r=reasons(t);return `${a}: оценка риска ${t.score.toFixed(1)} из 100. ${r.length?'Наблюдаемые признаки: '+r.join('; ')+'.':'Выраженных аномалий по заполненным признакам не обнаружено.'} ${a==='Challenge'?'Нужна дополнительная проверка обстоятельств платежа; одна 2FA не исключает социальную инженерию.':a==='Block'?'Перед исполнением платежа требуется проверка аналитиком.':'Результат не гарантирует отсутствие мошенничества.'}`;}
  function factorsHTML(t){const p=C.predict(t,state.model),f=p.factors.filter(x=>x.value!==0).sort((a,b)=>Math.abs(b.contribution)-Math.abs(a.contribution)).slice(0,5),max=Math.max(1,...f.map(x=>Math.abs(x.contribution)));return f.map(f=>`<div class="factor"><span>${escape(f.name)}</span><div class="factor-track"><i style="width:${Math.abs(f.contribution)/max*100}%"></i></div><b>${f.contribution>=0?'+':''}${f.contribution.toFixed(2)}</b></div>`).join('')+'<p class="small muted">Вклады линейной модели в log-odds, не проценты и не SHAP. База: '+state.model.intercept.toFixed(2)+'. Полный итог: '+p.logit.toFixed(2)+'.</p>';}
  function report(t){const p=C.predict(t,state.model);return `ICHNORA · ОТЧЁТ ПО ОПЕРАЦИИ\n${t.id} / ${t.timestamp}\nПользователь: ${t.user}\nСумма: ${t.amount} KZT\nПолучатель: ${t.merchant}\nИсточник: ${state.source}\n\n${explanation(t)}\n\nМодель: логистическая регрессия, обучение на синтетике.\nБазовый log-odds: ${state.model.intercept}\n`+p.factors.map(f=>`${f.name}: ${f.contribution.toFixed(6)}`).join('\n')+'\n\nЭто учебная оценка, а не подтверждённый факт мошенничества.';}
  function audit(t){$('audit-content').innerHTML=`<div class="panel-head"><div><p class="eyebrow">EXPLAINABILITY AUDIT</p><h2 id="audit-title">${escape(t.id)}</h2>${badge(C.action(t.score,state.policy))}</div><button class="close" id="close-audit" aria-label="Закрыть отчёт">×</button></div><div class="audit-meta">${[['Сумма',money(t.amount)],['Обычная сумма',money(t.average)],['Страна',country(t.country)],['Устройство',t.device],['IP (поле данных)',t.ip],['Получатель',t.merchant],['Метка фрода',t.label===null?'Неизвестна':t.label?'1 · фрод':'0 · легитимная'],['Время UTC',t.timestamp]].map(([a,b])=>`<div><small>${a}</small>${escape(b)}</div>`).join('')}</div><p class="explanation">${escape(explanation(t))}</p><h3>Главные факторы модели</h3>${factorsHTML(t)}<div class="btn-row"><button id="report-txt" class="primary">↓ Текстовый отчёт</button><button id="report-csv">↓ CSV</button><button id="report-print">Печать / PDF</button></div>`;
    $('close-audit').onclick=()=>$('audit').close();$('report-txt').onclick=()=>download(report(t),'ichnora-report.txt');$('report-csv').onclick=()=>download(C.exportCSV([t],state.policy),'ichnora-operation.csv','text/csv;charset=utf-8');$('report-print').onclick=()=>window.print();$('audit').showModal();
  }
  function simulator(){
    $('app').innerHTML=`<div class="section-grid"><section class="panel"><p class="eyebrow">LIVE DEMO</p><h2>Проверить новую операцию</h2><div class="presets"><button data-preset="safe">Безопасная покупка</button><button data-preset="takeover">Взлом аккаунта</button><button data-preset="social">Социальная инженерия</button><button data-preset="travel">Клиент в поездке</button></div><form id="sim-form"><div class="form-row"><label class="field">Сумма, ₸<input name="amount" type="number" min="1" max="1000000000" value="12000" required></label><label class="field">Средняя сумма клиента, ₸<input name="average" type="number" min="1" max="1000000000" value="15000" required></label><label class="field">Страна операции<select name="country">${options('KZ')}</select></label><label class="field">Обычная страна клиента<select name="home">${options('KZ')}</select></label><label class="field">Дата и время UTC<input name="timestamp" type="datetime-local" value="2026-09-19T12:00" required></label><label class="field">Операций за 10 минут<input name="frequency" type="number" min="0" max="10000" value="1" required></label><label class="field">Получатель<input name="merchant" value="Market-12" maxlength="100" required></label><label class="field">Устройство<input name="device" value="iPhone 14" maxlength="100" required></label><label class="field">Скорость смены IP<select name="ipChangeRate"><option value="stable" selected>Стабильная · IP не менялся</option><option value="recent">Недавняя · один раз за сессию</option><option value="rapid">Высокая · несколько смен за минуты</option></select><small>Высокая скорость добавляет сигнал Proxy/VPN.</small></label><label class="field">Пользователь<input name="user" value="U-DEMO" maxlength="80" required></label></div><div class="checks"><label><input name="newDevice" type="checkbox">Новое устройство</label><label><input name="newMerchant" type="checkbox">Новый получатель</label></div><button class="primary" type="submit">Рассчитать риск →</button><div id="sim-error" role="alert"></div></form></section><section class="panel" id="sim-result"><p class="eyebrow">РЕЗУЛЬТАТ АНАЛИЗА</p><h2>Готов к проверке</h2><p class="muted">Выберите сценарий или введите параметры. Результат использует ту же модель и пороги, что дашборд.</p></section></div>`;
    const form=$('sim-form');document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const presets={safe:{amount:12000,average:15000,frequency:1,country:'KZ',home:'KZ',ipChangeRate:'stable',newDevice:false,newMerchant:false,merchant:'Market-12',device:'iPhone 14'},takeover:{amount:850000,average:15000,frequency:14,country:'BR',home:'KZ',ipChangeRate:'rapid',newDevice:true,newMerchant:true,merchant:'Transfer-99',device:'Unknown Android'},social:{amount:900000,average:15000,frequency:19,country:'KZ',home:'KZ',ipChangeRate:'recent',newDevice:false,newMerchant:true,merchant:'New-recipient',device:'iPhone 14'},travel:{amount:24000,average:15000,frequency:1,country:'TR',home:'KZ',ipChangeRate:'stable',newDevice:false,newMerchant:false,merchant:'Travel-4',device:'iPhone 14'}};for(const [key,value]of Object.entries(presets[b.dataset.preset])){const input=form.elements.namedItem(key);if(input.type==='checkbox')input.checked=value;else input.value=value;}form.requestSubmit();});
    form.onsubmit=e=>{e.preventDefault();try{const v=Object.fromEntries(new FormData(form));const timestamp=new Date(v.timestamp+'Z');if(!Number.isFinite(+timestamp))throw Error('Проверьте дату и время.');const tx={...v,amount:+v.amount,average:+v.average,frequency:+v.frequency,timestamp:timestamp.toISOString(),newDevice:form.elements.newDevice.checked,vpn:v.ipChangeRate==='rapid',newMerchant:form.elements.newMerchant.checked,ip:'SIM-IP-'+v.ipChangeRate,id:'SIM-'+(++state.sequence),label:null};if(!tx.user.trim()||!tx.merchant.trim()||!tx.device.trim())throw Error('Заполните текстовые поля.');tx.score=C.predict(tx,state.model).score;state.last=tx;$('sim-error').innerHTML='';renderResult(tx);}catch(err){$('sim-error').innerHTML='<p class="feedback error">'+escape(err.message)+'</p>';}};
    if(state.last)renderResult(state.last);
  }
  function renderResult(t){const a=C.action(t.score,state.policy),color=a==='Block'?'red':a==='Challenge'?'amber':'green';$('sim-result').innerHTML=`<p class="eyebrow">ЛОКАЛЬНАЯ ML-МОДЕЛЬ</p><div class="sim-risk-score ${color}" aria-label="Risk score ${t.score.toFixed(0)} percent"><strong>${t.score.toFixed(0)}%</strong><span>RISK SCORE</span></div>${badge(a)}<p class="explanation">${escape(explanation(t))}</p>${factorsHTML(t)}<div class="btn-row"><button id="add-operation" class="primary" ${state.data.some(x=>x.id===t.id)?'disabled':''}>Добавить в мониторинг</button><button id="sim-audit">Открыть отчёт</button></div><div class="result-meta">Метка фрода неизвестна: эта операция не участвует в расчёте Precision, Recall и FPR. Название страны и получателя само по себе не является доказательством мошенничества.</div>`;$('add-operation').onclick=()=>{state.data.push(t);recompute();$('add-operation').disabled=true;toast('Операция добавлена в таблицу, статистику и карту.');};$('sim-audit').onclick=()=>audit(t);}
  function geography(){const result=new Map();for(const t of state.data){if(!result.has(t.country))result.set(t.country,{count:0,flagged:0,blocked:0,sum:0,score:0});const r=result.get(t.country),a=C.action(t.score,state.policy);r.count++;r.score+=t.score;r.sum+=t.amount;if(a!=='Approve')r.flagged++;if(a==='Block')r.blocked++;}return result;}
  function project([lon,lat]){return [(lon+180)*1000/360,(90-lat)*500/180];}
  function geoPath(geometry){const polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.coordinates;return polygons.map(poly=>poly.map(ring=>ring.map((point,i)=>{const [x,y]=project(point);return (i?'L':'M')+x.toFixed(2)+','+y.toFixed(2);}).join(' ')+'Z').join(' ')).join(' ');}
  function analytics(){
    $('app').innerHTML=`<div class="stack"><section class="panel"><div class="panel-head"><div><p class="eyebrow">GEO ANOMALIES</p><h2>Карта операций по всему миру</h2></div><span class="tag">OFFLINE MAP</span></div><div class="map-controls"><button id="zoom-in" aria-label="Увеличить карту">＋</button><button id="zoom-out" aria-label="Уменьшить карту">−</button><button id="zoom-reset">Весь мир</button><label class="field" style="flex:1">Показатель<select id="map-mode"><option value="count">Количество Challenge + Block</option><option value="rate">Доля Challenge + Block</option></select></label><label class="field" style="flex:1">Страна / территория<select id="map-country">${options(state.selectedCountry)}</select></label></div><div class="map-grid"><div><div class="map-frame"><svg id="world" class="world" viewBox="0 0 1000 500" role="group" aria-label="Интерактивная карта мира, выберите страну"><g id="world-layer"></g></svg></div><div class="chart-legend"><span>Тёмный: нет проверок</span><span class="amber">Золотой: больше проверок</span><span class="green">Мятный: выбранная страна</span></div><div id="country-detail" class="country-card"></div></div><div><h3>Страны с проверками</h3><div id="country-list" class="country-list"></div></div></div><p class="small muted" style="margin-top:15px">Карта агрегирует операции по странам, а не определяет местоположение IP. Для малых территорий используйте список. Контуры: <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth, public domain</a>; география не означает оценку надёжности страны.</p></section>
    <section class="panel"><div class="panel-head"><div><p class="eyebrow">LINK ANALYSIS</p><h2>Общие IP и устройства</h2></div><label class="field">Группировать по<select id="link-type"><option value="ip">IP</option><option value="device">Устройству</option></select></label></div><p class="muted">Совпадение связывает события, но не доказывает мошенническую сеть: IP может быть общим у офиса или VPN.</p><label class="field">Группа<select id="link-group"></select></label><div id="network"></div></section></div>`;
    $('map-mode').value=state.mapMode;$('map-mode').onchange=e=>{state.mapMode=e.target.value;renderMap();};$('map-country').onchange=e=>selectCountry(e.target.value);
    $('zoom-in').onclick=()=>{state.zoom=Math.min(5,state.zoom*1.4);transformMap();};$('zoom-out').onclick=()=>{state.zoom=Math.max(1,state.zoom/1.4);if(state.zoom===1)state.pan=[0,0];transformMap();};$('zoom-reset').onclick=()=>{state.zoom=1;state.pan=[0,0];transformMap();};
    const svg=$('world');let drag=null;svg.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,pan:[...state.pan],moved:false};};svg.onpointermove=e=>{if(!drag||state.zoom===1)return;const dx=(e.clientX-drag.x)*1000/svg.getBoundingClientRect().width,dy=(e.clientY-drag.y)*500/svg.getBoundingClientRect().height;if(Math.abs(dx)+Math.abs(dy)>5)drag.moved=true;state.pan=[drag.pan[0]+dx,drag.pan[1]+dy];transformMap();};svg.onpointerup=()=>{if(drag?.moved){svg.dataset.dragged='1';setTimeout(()=>delete svg.dataset.dragged,100);}drag=null;};svg.onpointerleave=()=>drag=null;
    $('link-type').onchange=renderNetworkGroups;renderMap();renderNetworkGroups();
  }
  function transformMap(){const z=state.zoom;state.pan=state.pan.map((n,i)=>Math.max(-(z-1)*(i?250:500),Math.min((z-1)*(i?250:500),n)));$('world-layer').setAttribute('transform',`translate(${500*(1-z)+state.pan[0]},${250*(1-z)+state.pan[1]}) scale(${z})`);}
  function renderMap(){const stats=geography(),map=globalThis.WORLD_MAP||[];const value=s=>!s?0:state.mapMode==='rate'?s.flagged/s.count:s.flagged;const max=Math.max(1e-9,...[...stats.values()].map(value));
    $('world-layer').innerHTML=map.map(f=>{const s=stats.get(f.code),v=value(s)/max,fill=v?`rgb(${Math.round(36+v*170)},${Math.round(58+v*113)},${Math.round(73+v*31)})`:'#152b3f';return `<path d="${geoPath(f.geometry)}" fill="${fill}" fill-rule="evenodd" data-country="${escape(f.code)}" tabindex="0" role="button" aria-label="${escape(C.codes.includes(f.code)?country(f.code):f.name)}"><title>${escape(C.codes.includes(f.code)?country(f.code):f.name)} · ${num(s?.flagged||0)} проверок</title></path>`;}).join('');
    document.querySelectorAll('[data-country]').forEach(el=>{el.onclick=()=>{if(!$('world').dataset.dragged&&C.codes.includes(el.dataset.country))selectCountry(el.dataset.country);};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}};});
    $('country-list').innerHTML=[...stats].sort((a,b)=>value(b[1])-value(a[1])).slice(0,30).map(([c,s])=>`<button data-select-country="${c}"><span>${escape(country(c))}</span><small>${num(s.flagged)} · ${percent(s.flagged/s.count)}</small></button>`).join('');document.querySelectorAll('[data-select-country]').forEach(b=>b.onclick=()=>selectCountry(b.dataset.selectCountry));transformMap();selectCountry(state.selectedCountry);
  }
  function selectCountry(c){state.selectedCountry=c;$('map-country').value=c;document.querySelectorAll('[data-country]').forEach(el=>el.classList.toggle('map-selected',el.dataset.country===c));const s=geography().get(c);$('country-detail').innerHTML=`<h3>${escape(country(c))} <span class="muted">${c}</span></h3>${s?`Операций: <strong>${num(s.count)}</strong> · Проверок: <strong>${num(s.flagged)}</strong> · Block: <strong>${num(s.blocked)}</strong><br>Средний риск: ${(s.score/s.count).toFixed(1)} / 100 · Объём: ${money(s.sum)}<div style="margin-top:12px"><button id="country-transactions">Открыть операции →</button></div>`:'В текущем наборе нет операций из этой страны или территории.'}`;if($('country-transactions'))$('country-transactions').onclick=()=>{Object.assign(state,{filterCountry:c,query:'',filterAction:'',filterDevice:'',filterDate:'',minRisk:0,page:0});location.hash='transactions';};}
  let networkGroups=[];
  function renderNetworkGroups(){const key=$('link-type').value,groups=new Map();for(const t of state.data){if(!t[key]||t[key]==='Unknown')continue;if(!groups.has(t[key]))groups.set(t[key],{key:t[key],users:new Set(),tx:[],flagged:0});const g=groups.get(t[key]);g.users.add(t.user);g.tx.push(t);if(C.action(t.score,state.policy)!=='Approve')g.flagged++;}networkGroups=[...groups.values()].filter(g=>g.users.size>1).sort((a,b)=>b.flagged-a.flagged).slice(0,30);$('link-group').innerHTML=networkGroups.map((g,i)=>`<option value="${i}">${escape(g.key)} · ${num(g.users.size)} пользователей · ${num(g.flagged)} проверок</option>`).join('')||'<option>Совпадений не найдено</option>';$('link-group').onchange=renderNetwork;renderNetwork();}
  function renderNetwork(){const g=networkGroups[+$('link-group').value];if(!g){$('network').innerHTML='<div class="empty">Нет общих идентификаторов у разных пользователей.</div>';return;}const users=[...g.users].slice(0,12),cx=350,cy=155;let lines='',nodes='';users.forEach((u,i)=>{const angle=i/users.length*Math.PI*2,x=cx+245*Math.cos(angle),y=cy+110*Math.sin(angle);lines+=`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}"/>`;nodes+=`<g><circle cx="${x}" cy="${y}" r="23"/><text x="${x}" y="${y+40}">${escape(u)}</text></g>`;});$('network').innerHTML=`<svg class="network-svg" viewBox="0 0 700 340" role="img" aria-label="Связи пользователей через общий идентификатор">${lines}${nodes}<circle cx="350" cy="155" r="40"/><text x="350" y="150">Общий</text><text x="350" y="170">${escape($('link-type').value)}</text></svg><p class="muted">${escape(g.key)} · ${num(g.tx.length)} операций · показаны ${users.length} из ${num(g.users.size)} пользователей.</p><button id="network-transactions">Показать связанные операции</button>`;$('network-transactions').onclick=()=>{Object.assign(state,{query:$('link-type').value+':'+g.key,filterCountry:'',filterAction:'',filterDevice:'',filterDate:'',minRisk:0,page:0});location.hash='transactions';};}
  function upload(){
    $('app').innerHTML=`<div class="stack"><section class="panel"><div class="panel-head"><div><p class="eyebrow">DATA PIPELINE</p><h2>Загрузить транзакции</h2></div><button id="template">↓ Пример CSV</button></div><div class="data-state"><span>${escape(state.source)}</span><strong>${num(state.data.length)} операций</strong></div><label class="upload-zone" id="drop-zone"><span>↥</span><strong>Выберите CSV или перетащите сюда</strong><p class="muted">До 100 000 строк · максимум 50 МБ · обработка на этом компьютере</p><input id="csv-file" type="file" accept=".csv,text/csv"></label><div id="upload-feedback" role="status" aria-live="polite"></div><div class="btn-row" style="margin-top:20px"><button id="restore">Вернуть 100 000 демоопераций</button><button id="export-data">Выгрузить текущие данные</button></div><p class="small muted">Загрузка заменяет текущий набор в памяти. При обновлении страницы снова появятся демоданные. Данные никуда не отправляются.</p></section>
    <section class="panel method"><h2>Схема CSV</h2><p>Кнопка «Пример CSV» скачает готовый совместимый файл. Поддерживаются разделители запятая и точка с запятой, UTF-8, поля в кавычках.</p><p><code>id, user, amount, average, country, home, timestamp, frequency, new_device, vpn, new_merchant</code> — обязательные столбцы.</p><p><code>merchant, device, ip, label</code> — дополнительные. Страны: двухбуквенные ISO-коды, например KZ, US, JP. Флаги: 0/1. Время: ISO 8601 с часовым поясом. <code>label</code>: 1 = фрод, 0 = легитимная, пусто = неизвестно.</p><p>Средняя сумма <code>average</code> и флаги новизны должны описывать только историю, известную до операции. Скоринг не использует будущие метки.</p></section>
    <section class="panel method"><h2>Что именно измеряет прототип</h2><ul><li>Модель: логистическая регрессия, обученная локально на 12 000 отдельных синтетических примеров. Проверочный набор из 100 000 операций генерируется другим seed и не используется для обучения.</li><li>Факторы: сумма относительно обычной, частота, новое устройство, смена страны, VPN, новизна получателя, время UTC и комбинация устройства с VPN.</li><li>Оценка 0–100 отражает модель синтетического мира. Это не проверенная вероятность для банковских данных.</li><li>XAI показывает точные аддитивные вклады модели в log-odds. Объяснения создаются локальным шаблоном, без LLM и без вымышленных SHAP-процентов.</li><li>FPR = FP / (FP + TN); Precision = TP / (TP + FP); Recall = TP / (TP + FN). Положительное решение в этих метриках — Block. Строки без меток исключены из оценки качества.</li><li>Cost = остаточная сумма фрода + цена ложных блокировок + цена проверок. Эффект Challenge — настраиваемое допущение. AP — ступенчатая площадь Precision–Recall, ROC-AUC считается по парам FPR/TPR.</li><li>Страны: 249 кодов ISO 3166-1, включая территории. Офлайн-карта Natural Earth 1:110m упрощена и не показывает отдельными контурами все малые территории.</li></ul><details><summary>Что ещё требуется до банковского внедрения и финальной защиты</summary><p>Обучить и проверить модель на датасете организаторов, проверить временное разделение, стоимость ошибок и калибровку. Подключить серверный API к рабочей модели; добавить авторизацию и журнал аналитика. Текущий локальный интерфейс не вызывает старый backend/main.py. Деплой, презентация, видео и публикация в AI Startify — отдельные этапы.</p></details></section></div>`;
    $('template').onclick=()=>download(C.exportCSV(C.scoreData(C.generate(8,887,'SAMPLE'),state.model),state.policy),'ichnora-sample.csv','text/csv;charset=utf-8');$('export-data').onclick=()=>download(C.exportCSV(state.data,state.policy),'ichnora-data.csv','text/csv;charset=utf-8');
    $('restore').onclick=()=>{state.data=C.scoreData(C.generate(100000),state.model);state.source='Синтетический набор';state.page=0;recompute();upload();toast('Демонстрационный набор восстановлен.');};
    $('csv-file').onchange=e=>loadFile(e.target.files[0]);const zone=$('drop-zone');zone.ondragover=e=>{e.preventDefault();zone.classList.add('drag');};zone.ondragleave=()=>zone.classList.remove('drag');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('drag');loadFile(e.dataTransfer.files[0]);};
  }
  async function loadFile(file){if(!file)return;const feedback=$('upload-feedback');try{if(!file.name.toLowerCase().endsWith('.csv'))throw Error('Нужен файл CSV. Parquet пока не поддерживается.');if(file.size>50*1024*1024)throw Error('Файл больше 50 МБ.');feedback.className='feedback';feedback.textContent='Читаем и проверяем файл…';const text=await file.text();const parsed=C.parseCSV(text);C.scoreData(parsed,state.model);state.data=parsed;state.source='CSV: '+file.name;state.page=0;recompute();if(route==='upload'){upload();$('upload-feedback').className='feedback';$('upload-feedback').textContent=`Загружено ${num(parsed.length)} операций. Метрики, таблица и карта обновлены.`;}toast('CSV успешно загружен.');}catch(err){feedback.className='feedback error';feedback.textContent=err.message;}}
  function render(){stopStream();route=location.hash.slice(1);if(!['dashboard','transactions','simulator','analytics','upload'].includes(route))route='dashboard';document.querySelectorAll('[data-route]').forEach(a=>{if(a.dataset.route===route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('page-title').textContent={dashboard:'Панель риск-аналитика',transactions:'Мониторинг транзакций',simulator:'Симулятор операций',analytics:'География и связи',upload:'Данные и методика'}[route];({dashboard:dashboardHome,transactions,simulator,analytics,upload})[route]();}
  $('audit').onclick=e=>{if(e.target===$('audit')){const r=$('audit').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('audit').close();}};
  $('export-all').onclick=()=>download(C.exportCSV(state.data,state.policy),'ichnora-transactions.csv','text/csv;charset=utf-8');
  document.querySelectorAll('[data-language]').forEach(button=>button.onclick=()=>applyLanguage(button.dataset.language));applyLanguage(interfaceLanguage);
  setTimeout(()=>{try{state.model=C.train();state.data=C.scoreData(C.generate(100000),state.model);recompute();$('app').setAttribute('aria-busy','false');render();window.addEventListener('hashchange',render);}catch(e){$('app').innerHTML='<div class="feedback error">Не удалось подготовить приложение: '+escape(e.message)+'</div>';}},30);
})();
